services:
  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: hugo_blogtech_db
      MARIADB_USER: hugo_blogtech_user
      MARIADB_PASSWORD: hugo_blogtech_pwd
    volumes:
      - hugo_blogtech_db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  hugo_blogtech_db_data: